#spring:
#  profiles:
#    active: devo
#  r2dbc:
#    url: r2dbc:pool:mysql://localhost:3306
#    name: reactivedb
#    username: mysql
#    password: mysql
#  data:
#    r2dbc:
#      repositories:
#        enabled: true
#
#server:
#  port: 9091